"""Add relationship User, Website

Revision ID: db84b00fc37f
Revises: 89e64d676151
Create Date: 2025-07-06 12:47:58.867496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db84b00fc37f'
down_revision: Union[str, None] = '89e64d676151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        'fk_websites_user_id_users',
        'websites',
        'users',
        ['user_id'],
        ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_websites_user_id_users', 'websites', type_='foreignkey')
    # ### end Alembic commands ###
